const LINK_STORAGE_KEY=globalThis.CARDPICK_LINK_STORAGE_KEY||'card-pick-link-watch-v1';
const APP_STORAGE_KEY=globalThis.CARDPICK_STORAGE_KEY||'card-pick-state-v1';
const FALLBACK_ISSUERS=['신한카드','삼성카드','롯데카드'];
const app=document.querySelector('#app');
let selectedIssuer=null,draft=[],pastedText='',enhanceTimer=null;

function localMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function monthLabel(month=localMonth()){const [y,m]=month.split('-');return `${Number(y)}년 ${Number(m)}월`}
function emptyStore(){return {version:1,month:localMonth(),issuers:{}}}
function loadStore(){let store;try{store=JSON.parse(localStorage.getItem(LINK_STORAGE_KEY)||'null')}catch{store=null}if(!store||store.month!==localMonth()){store=emptyStore();localStorage.setItem(LINK_STORAGE_KEY,JSON.stringify(store))}if(!store.issuers||typeof store.issuers!=='object')store.issuers={};return store}
function saveStore(store){store.version=1;store.month=localMonth();localStorage.setItem(LINK_STORAGE_KEY,JSON.stringify(store))}
function getIssuers(){try{const state=JSON.parse(localStorage.getItem(APP_STORAGE_KEY)||'null');const issuers=[...new Set((state?.cards||[]).map(c=>c.issuer).filter(Boolean))];if(issuers.length)return issuers}catch{}return FALLBACK_ISSUERS}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function normalizeSpaces(v=''){return String(v).replace(/\u00a0/g,' ').replace(/[ \t]+/g,' ').trim()}
function merchantKey(v=''){return String(v).toLowerCase().normalize('NFKC').replace(/\(주\)|주식회사|㈜/g,'').replace(/[\s·ㆍ._\-–—/\\()[\]{}'"`:;,!?]/g,'').replace(/×/g,'x')}
function levenshtein(a,b){if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur}return prev[b.length]}
function merchantMatches(input,stored){const a=merchantKey(input),b=merchantKey(stored);if(!a||!b)return false;if(a===b||a.includes(b)||b.includes(a))return true;if(a.length>=4&&b.length>=4&&Math.abs(a.length-b.length)<=1&&levenshtein(a,b)<=1)return true;if(a.includes('네이버')&&b.includes('네이버')&&a.includes('스토어')&&b.includes('스토어'))return true;return false}

const PAYMENT_TERMS=['삼성페이','네이버페이','카카오페이','페이코','PAYCO','애플페이','Apple Pay','구글페이','Google Pay','간편결제'];
function splitPaymentQualifier(raw){let text=normalizeSpaces(raw).replace(/^[\-–—•·]+|[\-–—•·]+$/g,'').trim();for(const term of PAYMENT_TERMS){const escaped=term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const cross=new RegExp(`^(.*?)[xX×]\\s*(${escaped})$`,'i');const m=text.match(cross);if(m&&m[1].trim())return {name:m[1].trim(),note:`${m[2]} 조건`}}return {name:text,note:''}}
function cleanCandidate(raw){let s=normalizeSpaces(raw);s=s.split(/\n/).pop().trim();s=s.replace(/^.*?\d{1,3}(?:,\d{3})*\s*원\s*(?:캐시백|청구할인|할인|적립|포인트|쿠폰)?\s*/i,'');s=s.replace(/^.*?\d+(?:\.\d+)?\s*%\s*(?:캐시백|청구할인|할인|적립)?\s*/i,'');s=s.replace(/^(?:캐시백|청구할인|할인|적립|포인트|쿠폰|혜택)\s*/i,'');s=s.replace(/\s*(?:더한\s*후|추가한\s*후|추가\s*후|응모한\s*후|응모\s*후|혜택\s*추가\s*후).*$/i,'');s=s.replace(/\s*(?:건\s*별|결제\s*시|이용\s*시|기간\s*내|월\s*\d+\s*회|\d{4}[.\-/]\d{1,2}).*$/i,'');s=s.replace(/[,:;|]+$/,'').trim();if(s.length<2||s.length>60)return null;if(/^(신한|삼성|롯데|현대|KB|국민|하나|우리)?\s*카드$/i.test(s))return null;if(/^(캐시백|할인|적립|결제|혜택|기간)$/i.test(s))return null;if(/^\d[\d,]*(?:원|%)?$/.test(s))return null;return splitPaymentQualifier(s)}
function detectDateNote(context=''){const s=normalizeSpaces(context);const patterns=[/단\s*하루/g,/하루만/g,/특정일/g,/당일\s*(?:한정|만)?/g,/매주\s*[월화수목금토일]\s*요일/g,/[월화수목금토일]\s*요일\s*(?:한정|만)/g,/\d{1,2}[./월]\s*\d{1,2}(?:일)?\s*(?:에만|만|한정)/g];for(const re of patterns){const m=s.match(re);if(m?.[0])return m[0]}return ''}
function addCandidate(out,raw,context){const c=cleanCandidate(raw);if(!c?.name)return;const key=merchantKey(c.name);if(!key)return;const existing=out.find(x=>merchantKey(x.name)===key),dateNote=detectDateNote(context);if(existing){if(!existing.note&&c.note)existing.note=c.note;if(!existing.dateNote&&dateNote)existing.dateNote=dateNote;return}out.push({id:crypto.randomUUID?.()||`${Date.now()}-${out.length}`,name:c.name,note:c.note||'',dateNote,selected:true})}
export function extractLinkMerchants(input=''){const text=String(input).replace(/\r/g,'\n').replace(/\n{2,}/g,'\n'),out=[];const optIn=/([^\n]{1,100}?)\s*(?:더한\s*후|추가한\s*후|추가\s*후|응모한\s*후|응모\s*후|혜택\s*추가\s*후)/gi;let m;while((m=optIn.exec(text)))addCandidate(out,m[1],m[0]);for(const line0 of text.split(/\n+/)){const line=normalizeSpaces(line0);if(!line)continue;const benefitStart=line.match(/^\s*(?:\S+\s+){0,2}(?:\d{1,3}(?:,\d{3})*\s*원|\d+(?:\.\d+)?\s*%)\s*(?:캐시백|청구할인|할인|적립|포인트|쿠폰)?\s+(.+?)\s*(?=건\s*별|결제\s*시|이용\s*시|기간\s*내|\d{4}[.\-/]|$)/i);if(benefitStart)addCandidate(out,benefitStart[0],line)}return out}

function ensureStyles(){if(document.querySelector('#v13-link-styles'))return;const style=document.createElement('style');style.id='v13-link-styles';style.textContent=`
.link-v13-intro{background:#f4f1ff;border:1px solid #e4ddff;border-radius:16px;padding:14px 16px;margin-bottom:18px;line-height:1.5}.link-v13-month{font-weight:800}.link-v13-issuers{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0 18px}.link-v13-issuer{border:1px solid #d0d5dd;background:#fff;border-radius:14px;padding:13px 8px;font-weight:800;color:#344054}.link-v13-issuer.active{border:2px solid #6938ef;color:#5925dc;background:#f9f5ff;padding:12px 7px}.link-v13-textarea{width:100%;min-height:220px;resize:vertical;border:1.5px solid #7f56d9;border-radius:14px;padding:14px;font:inherit;line-height:1.55;background:#fff;box-sizing:border-box}.link-v13-help{margin:7px 0 12px}.link-v13-draft{margin-top:18px}.link-v13-draft-row{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding:12px 0;border-bottom:1px solid #eaecf0}.link-v13-draft-row input[type=checkbox]{width:20px;height:20px;accent-color:#6938ef}.link-v13-name{width:100%;border:0;background:transparent;font:inherit;font-weight:800;padding:4px 0;color:#101828}.link-v13-name:focus{outline:0;border-bottom:1px solid #7f56d9}.link-v13-note{font-size:12px;color:#667085;margin-top:2px}.link-v13-badge{display:inline-block;background:#f4f3ff;color:#5925dc;border-radius:999px;padding:4px 8px;font-size:11px;font-weight:800;white-space:nowrap}.link-v13-saved-card{margin:10px 0}.link-v13-chip{display:inline-flex;align-items:center;gap:5px;background:#f2f4f7;border-radius:999px;padding:6px 9px;margin:4px 4px 0 0;font-size:12px}.link-v13-count{color:#6938ef;font-weight:800}.link-v13-delete{border:0;background:none;color:#b42318;font-size:12px;font-weight:700;padding:8px}.link-watch-alert{border:1.5px solid #b692f6;background:#f9f5ff}.link-watch-title{font-weight:900;color:#5925dc;margin-bottom:8px}.link-watch-issuer{margin:7px 0}.link-watch-note{display:inline-block;background:#eee7ff;color:#5925dc;border-radius:999px;padding:3px 7px;font-size:11px;font-weight:800;margin-left:5px}@media(max-width:420px){.link-v13-issuers{grid-template-columns:1fr}.link-v13-textarea{min-height:190px}}`;document.head.appendChild(style)}
function showToast(message){const toast=document.querySelector('#toast');if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
function savedCount(store){return Object.values(store.issuers).reduce((n,arr)=>n+(arr?.length||0),0)}
function savedCardsHtml(store){const rows=getIssuers().filter(i=>(store.issuers[i]||[]).length).map(issuer=>{const items=store.issuers[issuer]||[];return `<section class="card link-v13-saved-card"><div class="list-head"><div><strong>${esc(issuer)}</strong><div class="small muted">${items.length}개 결제처</div></div><button class="link-v13-delete" data-delete-issuer="${esc(issuer)}">삭제</button></div><div>${items.map(x=>`<span class="link-v13-chip">${esc(x.name)}${x.note?` <span class="link-v13-badge">${esc(x.note)}</span>`:''}${x.dateNote?` <span class="link-v13-badge">특정일</span>`:''}</span>`).join('')}</div></section>`}).join('');return rows||'<div class="empty">이번 달 등록된 Link 결제처가 없습니다.</div>'}
function draftHtml(){if(!draft.length)return '';return `<section class="card link-v13-draft"><div class="list-head"><div><strong>감지된 결제처 (${draft.length}개)</strong><div class="small muted">틀린 이름은 바로 수정할 수 있습니다.</div></div><button type="button" class="ghost-button" id="linkAddRow">+ 추가</button></div>${draft.map((x,i)=>`<div class="link-v13-draft-row" data-draft-index="${i}"><input type="checkbox" class="link-draft-check" ${x.selected?'checked':''} aria-label="저장 선택"><div><input class="link-v13-name" value="${esc(x.name)}" aria-label="결제처 이름"><div class="link-v13-note">${x.note?esc(x.note):'추가 조건 없음'}${x.dateNote?` · ${esc(x.dateNote)}`:''}</div></div>${x.note||x.dateNote?`<span class="link-v13-badge">조건 감지</span>`:''}</div>`).join('')}<button type="button" class="primary-button" id="linkSaveDraft">선택한 결제처 저장하기</button></section>`}
function renderLinkScreen(){if(!app||!document.querySelector('.nav-item.active[data-route="links"]'))return;ensureStyles();const store=loadStore(),issuers=getIssuers();if(!selectedIssuer||!issuers.includes(selectedIssuer))selectedIssuer=issuers[0];app.innerHTML=`<div class="section-title"><div><h2>Link 혜택 등록</h2><p>카드사 앱에서 복사한 텍스트로 이번 달 결제처만 등록합니다.</p></div></div><div class="link-v13-intro"><div class="link-v13-month">${monthLabel(store.month)} Link 혜택</div><div class="small">Link 목록은 월별로 관리되며, 월이 바뀌면 이전 목록은 자동 삭제됩니다.</div></div><section class="card"><div class="field"><label>카드사 선택</label><div class="link-v13-issuers">${issuers.map(i=>`<button type="button" class="link-v13-issuer ${i===selectedIssuer?'active':''}" data-link-issuer="${esc(i)}">${esc(i)}</button>`).join('')}</div></div><div class="field"><label>Link 화면 텍스트 붙여넣기</label><div class="small muted link-v13-help">갤러리에서 텍스트를 추출한 뒤 전체 내용을 그대로 붙여넣으세요. 할인금액·횟수는 저장하지 않습니다.</div><textarea id="linkPasteText" class="link-v13-textarea" placeholder="여기에 카드사 Link 화면의 텍스트를 붙여넣으세요.">${esc(pastedText)}</textarea></div><button type="button" class="primary-button" id="linkExtract">결제처 자동 추출하기</button>${draftHtml()}</section><div class="section-title compact"><div><h2>이번 달 등록 현황</h2><p>총 <span class="link-v13-count">${savedCount(store)}개</span> 결제처</p></div></div>${savedCardsHtml(store)}`;bindLinkScreen()}
function bindLinkScreen(){app.querySelectorAll('[data-link-issuer]').forEach(b=>b.addEventListener('click',()=>{selectedIssuer=b.dataset.linkIssuer;draft=[];pastedText=app.querySelector('#linkPasteText')?.value||'';renderLinkScreen()}));app.querySelector('#linkPasteText')?.addEventListener('input',e=>{pastedText=e.target.value});app.querySelector('#linkExtract')?.addEventListener('click',()=>{pastedText=app.querySelector('#linkPasteText')?.value||'';draft=extractLinkMerchants(pastedText);renderLinkScreen();if(!draft.length)showToast('결제처를 찾지 못했습니다. 텍스트를 확인하거나 직접 추가하세요.')});app.querySelector('#linkAddRow')?.addEventListener('click',()=>{syncDraftInputs();draft.push({id:crypto.randomUUID?.()||String(Date.now()),name:'',note:'',dateNote:'',selected:true});renderLinkScreen()});app.querySelector('#linkSaveDraft')?.addEventListener('click',()=>{syncDraftInputs();const items=draft.filter(x=>x.selected&&x.name.trim()).map(({name,note,dateNote})=>({name:name.trim(),note,dateNote})),unique=[];for(const x of items)if(!unique.some(y=>merchantKey(y.name)===merchantKey(x.name)))unique.push(x);const store=loadStore();store.issuers[selectedIssuer]=unique;saveStore(store);draft=[];pastedText='';renderLinkScreen();showToast(`${selectedIssuer} Link ${unique.length}개를 저장했습니다.`)});app.querySelectorAll('[data-delete-issuer]').forEach(b=>b.addEventListener('click',()=>{const store=loadStore();delete store.issuers[b.dataset.deleteIssuer];saveStore(store);renderLinkScreen();showToast('해당 카드사 Link 목록을 삭제했습니다.')}))}
function syncDraftInputs(){app.querySelectorAll('[data-draft-index]').forEach(row=>{const i=Number(row.dataset.draftIndex),item=draft[i];if(!item)return;item.selected=!!row.querySelector('.link-draft-check')?.checked;item.name=row.querySelector('.link-v13-name')?.value||item.name})}
function currentWatchMatches(merchant){const store=loadStore(),matches=[];for(const [issuer,items] of Object.entries(store.issuers||{}))for(const item of items||[])if(merchantMatches(merchant,item.name))matches.push({issuer,...item});return matches}
function enhanceRecommendation(){if(!app||!document.querySelector('.nav-item.active[data-route="home"]'))return;app.querySelector('.link-watch-alert')?.remove();const merchant=app.querySelector('#recommendForm [name="merchant"]')?.value?.trim(),resultArea=app.querySelector('#resultArea');if(!merchant||!resultArea)return;const matches=currentWatchMatches(merchant);if(!matches.length)return;const byIssuer=new Map();for(const x of matches){if(!byIssuer.has(x.issuer))byIssuer.set(x.issuer,[]);byIssuer.get(x.issuer).push(x)}const section=document.createElement('section');section.className='card link-watch-alert';section.innerHTML=`<div class="link-watch-title">✦ Link 혜택 점검</div>${[...byIssuer].map(([issuer,items])=>`<div class="link-watch-issuer"><strong>${esc(issuer)}</strong>에 ${items.map(x=>`<b>${esc(x.name)}</b>${x.note?`<span class="link-watch-note">${esc(x.note)}</span>`:''}${x.dateNote?'<span class="link-watch-note">특정일 조건</span>':''}`).join(', ')} Link가 등록되어 있습니다.</div>`).join('')}<div class="small muted">기존 카드 추천금액에는 반영하지 않았습니다. 결제 전 카드사 앱에서 세부조건과 사용 여부를 확인하세요.</div>`;resultArea.prepend(section)}
function enhance(){loadStore();if(document.querySelector('.nav-item.active[data-route="links"]'))renderLinkScreen();else enhanceRecommendation()}
function scheduleEnhance(){clearTimeout(enhanceTimer);enhanceTimer=setTimeout(enhance,0)}
document.addEventListener('click',scheduleEnhance,false);document.addEventListener('submit',scheduleEnhance,false);document.addEventListener('change',scheduleEnhance,false);ensureStyles();enhance();
