 if(state.modal==='settle')return `<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>정산 추가</h2>${close}</div><form id="settleForm" class="form"><div class="form-grid"><div class="field"><label>일자</label><input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>대납 가정</label><select name="payer">${state.households.map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join('')}</select></div></div><div class="field"><label>내용</label><input name="description" required></div><div class="field"><label>총액</label><input id="settleTotal" name="total" type="number" min="0" required></div>${state.households.map(h=>`<div class="form-grid"><div class="field"><label>${esc(h.name)} 분담액</label><input name="share_${h.id}" type="number" min="0" value="0"></div><div class="field"><label>${esc(h.name)} 상태</label><select name="status_${h.id}"><option value="unpaid">미정산</option><option value="paid">완료</option><option value="self">본인</option><option value="excluded">-</option></select></div></div>`).join('')}<button class="btn">저장</button></form></div></div>`; return '';
}

function bindFileButtons(){document.querySelectorAll('.file-btn').forEach(b=>b.onclick=async()=>{const a=state.attachments.find(x=>x.id===b.dataset.file);if(!a)return;const {data,error}=await state.sb.storage.from('family-files').createSignedUrl(a.storage_path,60);if(error)return alert(error.message);window.open(data.signedUrl,'_blank','noopener');});}

function bindModal(){ $('#closeModal').onclick=()=>{state.modal=null;render();}; const tx=$('#txForm'),care=$('#careForm'),health=$('#healthForm'),settle=$('#settleForm'); if(tx){const type=tx.elements.type,cat=tx.elements.category;const fill=()=>cat.innerHTML=state.categories.filter(c=>c.type===type.value).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');type.onchange=fill;fill();tx.onsubmit=saveTx;} if(care)care.onsubmit=saveCare;if(health)health.onsubmit=saveHealth;if(settle){settle.onsubmit=saveSettlement;$('#settleTotal').onchange=()=>{const v=Math.round(Number($('#settleTotal').value||0)/3);state.households.forEach(h=>settle.elements[`share_${h.id}`].value=v);};}}
async function saveTx(e){e.preventDefault();const f=new FormData(e.target);const {error}=await state.sb.from('transactions').insert({family_id:state.family.id,txn_date:f.get('date'),type:f.get('type'),category_id:f.get('category')||null,description:f.get('description'),amount:Number(f.get('amount')),household_id:f.get('household')||null,payment_method:f.get('payment'),memo:f.get('memo')||null,created_by:state.session.user.id});if(error)return alert(error.message);await done();}
async function saveCare(e){e.preventDefault();const f=new FormData(e.target);const {data,error}=await state.sb.from('care_events').insert({family_id:state.family.id,event_date:f.get('date'),event_type:f.get('type'),place:f.get('place')||null,doctor:f.get('doctor')||null,companions:f.get('companions')||null,content:f.get('content')||null,memo:f.get('memo')||null,created_by:state.session.user.id}).select().single();if(error)return alert(error.message);const file=f.get('file');if(file&&file.size&&!f.get('protected')) return alert('의료 첨부파일은 파일 자체에 비밀번호를 설정한 뒤 체크해 주세요.');if(file&&file.size){const path=`${state.family.id}/${data.id}/${crypto.randomUUID()}-${file.name}`;const up=await state.sb.storage.from('family-files').upload(path,file,{upsert:false});if(up.error)return alert('기록은 저장됐지만 파일 업로드 실패: '+up.error.message);await state.sb.from('attachments').insert({family_id:state.family.id,care_event_id:data.id,storage_path:path,original_name:file.name,mime_type:file.type||null,password_protected:true,created_by:state.session.user.id});}await done();}
async function saveHealth(e){e.preventDefault();const f=new FormData(e.target),num=n=>f.get(n)?Number(f.get(n)):null;const {error}=await state.sb.from('health_logs').insert({family_id:state.family.id,log_date:f.get('date'),weight_kg:num('weight'),wbc:num('wbc'),anc:num('anc'),neuropathy_score:num('neuropathy'),fatigue_score:num('fatigue'),meal_memo:f.get('memo')||null,created_by:state.session.user.id});if(error)return alert(error.message);await done();}
async function saveSettlement(e){e.preventDefault();const f=new FormData(e.target);const {data,error}=await state.sb.from('settlements').insert({family_id:state.family.id,settlement_date:f.get('date'),description:f.get('description'),total_amount:Number(f.get('total')),payer_household_id:f.get('payer'),created_by:state.session.user.id}).select().single();if(error)return alert(error.message);const rows=state.households.map(h=>({family_id:state.family.id,settlement_id:data.id,household_id:h.id,amount:Number(f.get(`share_${h.id}`)||0),status:f.get(`status_${h.id}`),created_by:state.session.user.id}));const r=await state.sb.from('settlement_shares').insert(rows);if(r.error)return alert(r.error.message);await done();}
async function done(){state.modal=null;await refreshData();render();}
boot();
